---
title: SEP
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: admin@sigmaetapi.com
description: 'Sigma Eta Pi, founded in 2010 at University of California Los Angeles,
  is the premier entrepreneurship fraternity on the West Coast.

'
baseurl: ''
url: http://ucla.sigmaetapi.com
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
sass:
  sass_dir: assets/_sass
  style: compressed
